# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37e7a243d52e9000acce1d0072048bd7459fb0945ffe8ef052fa3c5ff8472076027b88005c99de170c020de526d2b854661dc7c9ef093e679576eae2911717f2

test:
  secret_key_base: 5891ac8d0ad6593b32a95a9e697b0b669c1adb5ff912f1c06f8b91d180490ac4825a09a55d7c929d9fc214b5a47c2202825195058fbdff184abe305537e0197b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
